{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\sklearn\\ensemble\\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.\n",
      "  from numpy.core.umath_tests import inner1d\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "article 27953647  not found.\n",
      "article 27948541  not found.\n",
      "article 27943881  not found.\n",
      "article 27949797  not found.\n",
      "article 27955116  not found.\n",
      "article 27950623  not found.\n",
      "article 27945102  not found.\n",
      "clinical trial NCT02659670  not found.\n",
      "article 27198327  not found.\n"
     ]
    }
   ],
   "source": [
    "import articles.article_fetch as article_fetch\n",
    "import articles.articles_info as article_info\n",
    "from articles import article\n",
    "\n",
    "import csv\n",
    "import codecs\n",
    "\n",
    "import pandas as pd\n",
    "from classifiers.random_forest import RandomForest\n",
    "from classifiers.svm_classifier import SVMClassifier\n",
    "from classifiers.mlp_classifier import MLPClassifier\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.metrics import confusion_matrix, classification_report\n",
    "from sklearn.metrics import precision_recall_fscore_support\n",
    "\n",
    "import clinical_trials.clinical_trial_fetch as ct_fetch\n",
    "import clinical_trials.clinical_trials_info as ct_info\n",
    "from clinical_trials import clinical_trial\n",
    "\n",
    "import csv\n",
    "import csv_data.csv as csv_data\n",
    "\n",
    "from dataframe import create_dataframe\n",
    "from dataframe import calculate_attributes\n",
    "\n",
    "from common_functions import common_functions\n",
    "\n",
    "import pandas as pd\n",
    "\n",
    "import importlib\n",
    "\n",
    "# I get the gold standard\n",
    "gold_standard = pd.read_csv('ClinicalPmidsALL.csv', encoding = 'ISO-8859-1', sep = ';')\n",
    "\n",
    "# Now I change the common answer from string to numerical\n",
    "csv_data.numerical_answers(gold_standard)\n",
    "\n",
    "# Let's correct data on csv (common answer sometimes is not correct)\n",
    "csv_data.correctData(gold_standard)\n",
    "\n",
    "# I get all the clinical trials ID and I get the articles in xml\n",
    "Clinical_trials = ct_fetch.get_xml_doms(gold_standard['CT'].tolist())\n",
    "\n",
    "# I get all the PMID and I get the articles in xml\n",
    "PubMed_id_string = list(map(str, gold_standard['PMID'].tolist())) # I get the PMID as list of strings\n",
    "PubMed_articles = article_fetch.fetch_many_articles(PubMed_id_string, local=True) # It takes time to fetch the articles\n",
    "\n",
    "# Let's map every clinical trial to every article (and remove the one that are not present) and common answer\n",
    "df = create_dataframe.get_base_dataframe(gold_standard, Clinical_trials, PubMed_articles)\n",
    "\n",
    "# standard, spacy or stanford\n",
    "ct_org_sample = 'standard'\n",
    "ar_org_sample = 'spacy'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "#lam = gold_standard['CT']\n",
    "#lam.index[lam == 'NCT00003204'].tolist()[0]\n",
    "\n",
    "ct_last_names, ct_first_name_initials, ct_first_names = ct_info.get_all_name_parts(df['CT'].tolist(), gold_standard)\n",
    "\n",
    "df['ct_last_name'], df['ct_first_name_initial'], df['ct_first_name'] = [ct_last_names, ct_first_name_initials, ct_first_names]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "# print(sum(x is not None for x in ct_last_names))\n",
    "df = df.dropna().reset_index(drop = True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    }
   ],
   "source": [
    "ar_last_names, ar_first_name_initials, ar_first_names = article_info.get_all_name_parts(df['PubMed'].tolist(), gold_standard)\n",
    "\n",
    "df['ar_last_name'], df['ar_first_name_initial'], df['ar_first_name'] = [ar_last_names, ar_first_name_initials, ar_first_names]\n",
    "df.dropna().reset_index(drop = True)\n",
    "print()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "NCT00730210 doesn't have an organization.\n",
      "NCT02220283 doesn't have an organization.\n"
     ]
    }
   ],
   "source": [
    "# now that we have the base information, let's add other attributes\n",
    "\n",
    "# we get the organization of the principal investigator, so we don't need to pass his/her name\n",
    "ct_organization_names = ct_info.get_all_organization_names(df['CT'].tolist(), df['ct_last_name'].tolist(),\n",
    "                                                           df['ct_first_name_initial'].tolist(),\n",
    "                                                           sample=ct_org_sample)\n",
    "\n",
    "# Now we insert it in the dataframe\n",
    "if('ct_organization' not in df):\n",
    "    df.insert(6, 'ct_organization', ct_organization_names)\n",
    "    \n",
    "\n",
    "# I get the e-mails\n",
    "ct_mails = ct_info.get_all_mails(df['CT'].tolist(), df['ct_last_name'].tolist(), df['ct_first_name_initial'].tolist())\n",
    "\n",
    "if('ct_mail' not in df):\n",
    "    df.insert(7, 'ct_mail', ct_mails)\n",
    "    \n",
    "# I get the year\n",
    "ct_years = ct_info.get_all_years(df['CT'].tolist())\n",
    "    \n",
    "if('ct_year' not in df):\n",
    "    df.insert(8, 'ct_year', ct_years)\n",
    "    \n",
    "# I get the initials of the name\n",
    "ct_initials = ct_info.get_all_initials(df['ct_first_name'].tolist())\n",
    "\n",
    "if('ct_initials' not in df):\n",
    "    df.insert(9, 'ct_initials', ct_initials)\n",
    "    \n",
    "# I get the title\n",
    "ct_titles = ct_info.get_all_titles(df['CT'].tolist())\n",
    "\n",
    "if('ct_title' not in df):\n",
    "    df.insert(10, 'ct_title', ct_titles)\n",
    "    \n",
    "# I get the country and the city\n",
    "ct_countries, ct_cities = ct_info.get_all_countries_and_cities(df['CT'].tolist())\n",
    "\n",
    "if('ct_country' not in df):\n",
    "    df.insert(11, 'ct_country', ct_countries)\n",
    "    \n",
    "if('ct_city' not in df):\n",
    "    df.insert(12, 'ct_city', ct_cities)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "267\n"
     ]
    }
   ],
   "source": [
    "print(sum(x is not None for x in df['ct_mail']))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "475\n",
      "126\n"
     ]
    }
   ],
   "source": [
    "# Let's add the same attributes for the articles\n",
    "\n",
    "ar_organization_names, ar_locations = article_info.get_all_organizations_locations(df['PubMed'].tolist(),\n",
    "                                                           df['ar_last_name'].tolist(),\n",
    "                                                           df['ar_first_name_initial'].tolist(),\n",
    "                                                           sample = ar_org_sample)\n",
    "df['ar_organization'] = ar_organization_names\n",
    "\n",
    "ar_mails = article_info.get_all_mails(df['PubMed'].tolist(), df['ar_last_name'].tolist(),\n",
    "                                      df['ar_first_name_initial'].tolist())\n",
    "df['ar_mail'] = ar_mails\n",
    "\n",
    "ar_years = article_info.get_all_years(df['PubMed'].tolist())\n",
    "\n",
    "df['ar_year'] = ar_years\n",
    "\n",
    "ar_initials = article_info.get_all_initials(df['ar_first_name'])\n",
    "\n",
    "df['ar_initials'] = ar_initials\n",
    "\n",
    "ar_titles = article_info.get_all_titles(df['PubMed'].tolist())\n",
    "\n",
    "df['ar_title'] = ar_titles\n",
    "df['ar_location'] = ar_locations\n",
    "\n",
    "print(sum(x is not None for x in ar_organization_names))\n",
    "print(sum(x is not None for x in ar_mails))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "# I now calculate useful attributes for the classifiers\n",
    "first_name_equalities = calculate_attributes.get_string_arrays_similarity(df['ct_first_name'].tolist(),\n",
    "                                                                          df['ar_first_name'].tolist())\n",
    "organization_similarities, organization_type_equalities = calculate_attributes.get_organization_similarity_and_type_equality(df['ct_organization'].tolist(),\n",
    "                                                                             df['ar_organization'].tolist(),\n",
    "                                                                             ct_org_sample, ar_org_sample)\n",
    "email_equalities = calculate_attributes.get_arrays_equality(df['ct_mail'].tolist(), df['ar_mail'].tolist())\n",
    "year_differences = calculate_attributes.get_year_differences(df['ct_year'].tolist(), df['ar_year'].tolist())\n",
    "last_name_lengths = calculate_attributes.get_last_name_lengths(df['ct_last_name'].tolist())\n",
    "initials_equality = calculate_attributes.get_arrays_equality(df['ct_initials'].tolist(), df['ar_initials'].tolist())\n",
    "namespace_sizes = calculate_attributes.get_namespace_ambiguities(df['ct_last_name'].tolist(),\n",
    "                                                                 df['ct_first_name_initial'].tolist())\n",
    "country_equalities, city_equalities = calculate_attributes.get_location_equalities(df['ct_country'].tolist(),\n",
    "                                                                                   df['ct_city'].tolist(),\n",
    "                                                                                   df['ar_location'].tolist())\n",
    "\n",
    "# Let's add the attributes to the data frame\n",
    "df['first_name_equality'], df['organization_similarity'] = [first_name_equalities, organization_similarities]\n",
    "df['email_equality'], df['year_difference'] = [email_equalities, year_differences]\n",
    "df['last_name_length'], df['initials_equality'] = [last_name_lengths, initials_equality]\n",
    "df['namespace_size'], df ['country_equality'] = [namespace_sizes, country_equalities]\n",
    "df['city_equality'], df['organization_type_equality'] = [city_equalities, organization_type_equalities]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "from java_libraries import java_server\n",
    "\n",
    "clinical_trials = df['CT'].tolist()\n",
    "articles = df['PubMed'].tolist()\n",
    "\n",
    "server = java_server.JavaServer()\n",
    "\n",
    "jds = []\n",
    "sts = []\n",
    "for i in range(len(articles)):\n",
    "    ct_texts = clinical_trials[i].get_text()\n",
    "    ct_texts.append(clinical_trials[i].get_title())\n",
    "    ct_texts = \" \".join(ct_texts)\n",
    "\n",
    "    ar_texts = articles[i].get_text()\n",
    "    ar_texts.append(articles[i].get_title())\n",
    "    ar_texts = \" \".join(ar_texts)\n",
    "        \n",
    "    jd = [server.get_jds(ct_texts), server.get_jds(ar_texts)]\n",
    "    jds.append(jd)\n",
    "    st = [server.get_sts(ct_texts), server.get_sts(ar_texts)]\n",
    "    sts.append(st)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [],
   "source": [
    "server.close_server()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "max_precision = 0\n",
    "\n",
    "from dataframe import calculate_attributes\n",
    "\n",
    "for i in range(1,100):\n",
    "    jds_similarities = []\n",
    "    for j in range(len(jds)):\n",
    "        jds_similarities.append(calculate_attributes.get_jds_sts_basic_similarities(jds[j][0][:i],jds[j][1][:i]))\n",
    "    \n",
    "    df['jds_similarity'] = jds_similarities\n",
    "\n",
    "    # normalize\n",
    "    df['namespace_size'] = common_functions.normalize(df['namespace_size'])\n",
    "    df['last_name_length'] = common_functions.normalize(df['last_name_length'])\n",
    "    df['year_difference'] = common_functions.normalize(df['year_difference'])\n",
    "\n",
    "    # save csv\n",
    "    df_to_save = df.drop(['CT', 'PubMed', 'ct_last_name', 'ct_first_name_initial', 'ct_first_name',\n",
    "          'ct_organization', 'ct_mail', 'ct_year', 'ct_initials', 'ct_title', 'ct_country', 'ct_city', \n",
    "            'ar_last_name','ar_first_name_initial','ar_first_name','ar_organization', 'ar_mail', 'ar_initials',\n",
    "                  'ar_year', 'ar_title', 'ar_location'], axis = 1)\n",
    "    csv = df_to_save.to_csv(index=False)\n",
    "    file = codecs.open(\"dataframe.csv\", \"w\", \"utf-8\")\n",
    "    file.write(csv)\n",
    "    file.close()\n",
    "\n",
    "    # model\n",
    "    df_model = pd.read_csv('dataframe.csv', encoding = 'utf-8')\n",
    "    x = df_model.drop('common_answer', axis=1)\n",
    "    y = df_model['common_answer']\n",
    "\n",
    "    avg_precision = 0\n",
    "    for k in range(100):\n",
    "        x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.33, random_state = k)\n",
    "        classifier = RandomForest(0)\n",
    "        classifier.create_model(x_train, y_train)\n",
    "        pred = classifier.predict(x_test)\n",
    "        avg_precision += precision_recall_fscore_support(y_test, pred, average='weighted')[0]\n",
    "    avg_precision /= 100\n",
    "\n",
    "    print(\"i:\",i,\"average precision:\",avg_precision)\n",
    "\n",
    "    if avg_precision > max_precision:\n",
    "        max_precision = avg_precision\n",
    "        best_i = i\n",
    "        \n",
    "print(best_i)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "max_precision = 0\n",
    "\n",
    "for i in range(1,100):\n",
    "    jds_similarities = []\n",
    "    for j in range(len(jds)):\n",
    "        jds_similarities.append(calculate_attributes.get_jds_sts_percentage_similarities(jds[j][0][:i],jds[j][1][:i]))\n",
    "    \n",
    "    df['jds_similarity'] = jds_similarities\n",
    "\n",
    "    # normalize\n",
    "    df['namespace_size'] = common_functions.normalize(df['namespace_size'])\n",
    "    df['last_name_length'] = common_functions.normalize(df['last_name_length'])\n",
    "    df['year_difference'] = common_functions.normalize(df['year_difference'])\n",
    "\n",
    "    # save csv\n",
    "    df_to_save = df.drop(['CT', 'PubMed', 'ct_last_name', 'ct_first_name_initial', 'ct_first_name',\n",
    "          'ct_organization', 'ct_mail', 'ct_year', 'ct_initials', 'ct_title', 'ct_country', 'ct_city', \n",
    "            'ar_last_name','ar_first_name_initial','ar_first_name','ar_organization', 'ar_mail', 'ar_initials',\n",
    "                  'ar_year', 'ar_title', 'ar_location'], axis = 1)\n",
    "    csv = df_to_save.to_csv(index=False)\n",
    "    file = codecs.open(\"dataframe.csv\", \"w\", \"utf-8\")\n",
    "    file.write(csv)\n",
    "    file.close()\n",
    "\n",
    "    # model\n",
    "    df_model = pd.read_csv('dataframe.csv', encoding = 'utf-8')\n",
    "    x = df_model.drop('common_answer', axis=1)\n",
    "    y = df_model['common_answer']\n",
    "\n",
    "    avg_precision = 0\n",
    "    for k in range(100):\n",
    "        x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.33, random_state = k)\n",
    "        classifier = RandomForest(0)\n",
    "        classifier.create_model(x_train, y_train)\n",
    "        pred = classifier.predict(x_test)\n",
    "        avg_precision += precision_recall_fscore_support(y_test, pred, average='weighted')[0]\n",
    "    avg_precision /= 100\n",
    "\n",
    "    print(\"i:\",i,\"average precision:\",avg_precision)\n",
    "\n",
    "    if avg_precision > max_precision:\n",
    "        max_precision = avg_precision\n",
    "        best_i = i\n",
    "        \n",
    "print(best_i)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "max_precision = 0\n",
    "\n",
    "for i in range(1,100):\n",
    "    jds_similarities = []\n",
    "    for j in range(len(jds)):\n",
    "        jds_similarities.append(calculate_attributes.get_jds_sts_ranking_similarities(jds[j][0][:i],jds[j][1][:i]))\n",
    "    \n",
    "    df['jds_similarity'] = jds_similarities\n",
    "\n",
    "    # normalize\n",
    "    df['namespace_size'] = common_functions.normalize(df['namespace_size'])\n",
    "    df['last_name_length'] = common_functions.normalize(df['last_name_length'])\n",
    "    df['year_difference'] = common_functions.normalize(df['year_difference'])\n",
    "\n",
    "    # save csv\n",
    "    df_to_save = df.drop(['CT', 'PubMed', 'ct_last_name', 'ct_first_name_initial', 'ct_first_name',\n",
    "          'ct_organization', 'ct_mail', 'ct_year', 'ct_initials', 'ct_title', 'ct_country', 'ct_city', \n",
    "            'ar_last_name','ar_first_name_initial','ar_first_name','ar_organization', 'ar_mail', 'ar_initials',\n",
    "                  'ar_year', 'ar_title', 'ar_location'], axis = 1)\n",
    "    csv = df_to_save.to_csv(index=False)\n",
    "    file = codecs.open(\"dataframe.csv\", \"w\", \"utf-8\")\n",
    "    file.write(csv)\n",
    "    file.close()\n",
    "\n",
    "    # model\n",
    "    df_model = pd.read_csv('dataframe.csv', encoding = 'utf-8')\n",
    "    x = df_model.drop('common_answer', axis=1)\n",
    "    y = df_model['common_answer']\n",
    "\n",
    "    avg_precision = 0\n",
    "    for k in range(100):\n",
    "        x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.33, random_state = k)\n",
    "        classifier = RandomForest(0)\n",
    "        classifier.create_model(x_train, y_train)\n",
    "        pred = classifier.predict(x_test)\n",
    "        avg_precision += precision_recall_fscore_support(y_test, pred, average='weighted')[0]\n",
    "    avg_precision /= 100\n",
    "\n",
    "    print(\"i:\",i,\"average precision:\",avg_precision)\n",
    "\n",
    "    if avg_precision > max_precision:\n",
    "        max_precision = avg_precision\n",
    "        best_i = i\n",
    "        \n",
    "print(best_i)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1174, in send_command\n",
      "    self.socket.sendall(command.encode(\"utf-8\"))\n",
      "ConnectionResetError: [WinError 10054] Connessione in corso interrotta forzatamente dall'host remoto\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1014, in send_command\n",
      "    response = connection.send_command(command)\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1178, in send_command\n",
      "    \"Error while sending\", e, proto.ERROR_ON_SEND)\n",
      "py4j.protocol.Py4JNetworkError: Error while sending\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "i: 1 average precision: 0.8623513050483576\n",
      "i: 2 average precision: 0.874671198599299\n",
      "i: 3 average precision: 0.8789202433581603\n",
      "i: 4 average precision: 0.8866703757224255\n",
      "i: 5 average precision: 0.8855148504985801\n",
      "i: 6 average precision: 0.8824169682413325\n",
      "i: 7 average precision: 0.8838600744674077\n",
      "i: 8 average precision: 0.8850843584594454\n",
      "i: 9 average precision: 0.8841165118750487\n",
      "i: 10 average precision: 0.882348198786051\n",
      "i: 11 average precision: 0.8824125661405143\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "i: 12 average precision: 0.883428996204982\n",
      "i: 13 average precision: 0.883540513853113\n",
      "i: 14 average precision: 0.8845211354813904\n",
      "i: 15 average precision: 0.8826406244777452\n",
      "i: 16 average precision: 0.8836838972618187\n",
      "i: 17 average precision: 0.8846376273930099\n",
      "i: 18 average precision: 0.8853256606645179\n",
      "i: 19 average precision: 0.8836691603615514\n",
      "i: 20 average precision: 0.8839230891474892\n",
      "i: 21 average precision: 0.8837149769086229\n",
      "i: 22 average precision: 0.8824835544109534\n",
      "i: 23 average precision: 0.8836308339291334\n",
      "i: 24 average precision: 0.8846986084699897\n",
      "i: 25 average precision: 0.8842409671903079\n",
      "i: 26 average precision: 0.8850878969324191\n",
      "i: 27 average precision: 0.8845085613130125\n",
      "i: 28 average precision: 0.8843521838564993\n",
      "i: 29 average precision: 0.8845018554585435\n",
      "i: 30 average precision: 0.8843597853665054\n",
      "i: 31 average precision: 0.8845773165288178\n",
      "i: 32 average precision: 0.8846851013306761\n",
      "i: 33 average precision: 0.8852900619937588\n",
      "i: 34 average precision: 0.8854669529432965\n",
      "i: 35 average precision: 0.8842651367798287\n",
      "i: 36 average precision: 0.8841325795523375\n",
      "i: 37 average precision: 0.8835391649960256\n",
      "i: 38 average precision: 0.8827210970926458\n",
      "i: 39 average precision: 0.8824991785315632\n",
      "i: 40 average precision: 0.8830237782010991\n",
      "i: 41 average precision: 0.8828192403351245\n",
      "i: 42 average precision: 0.8835161025735256\n",
      "i: 43 average precision: 0.8830611722828463\n",
      "i: 44 average precision: 0.8829529882506912\n",
      "i: 45 average precision: 0.8829556428435135\n",
      "i: 46 average precision: 0.8821561319564437\n",
      "i: 47 average precision: 0.8832971267772811\n",
      "i: 48 average precision: 0.8834466405068444\n",
      "i: 49 average precision: 0.8833583310610525\n",
      "i: 50 average precision: 0.8829569871018069\n",
      "i: 51 average precision: 0.8833064259548508\n",
      "i: 52 average precision: 0.8834447438819355\n",
      "i: 53 average precision: 0.8837230149498521\n",
      "i: 54 average precision: 0.883590103138502\n",
      "i: 55 average precision: 0.8833223239624449\n",
      "i: 56 average precision: 0.8833498297238269\n",
      "i: 57 average precision: 0.8831111126857468\n",
      "i: 58 average precision: 0.884164911268455\n",
      "i: 59 average precision: 0.8834560999949815\n",
      "i: 60 average precision: 0.8830805233442537\n",
      "i: 61 average precision: 0.8833040202349287\n",
      "i: 62 average precision: 0.8828273745542901\n",
      "i: 63 average precision: 0.8836415779973079\n",
      "i: 64 average precision: 0.8835449165399679\n",
      "i: 65 average precision: 0.8830358695416299\n",
      "i: 66 average precision: 0.8837962225446553\n",
      "i: 67 average precision: 0.8838004376602959\n",
      "i: 68 average precision: 0.8839225456144298\n",
      "i: 69 average precision: 0.8838376774848927\n",
      "i: 70 average precision: 0.8835091473353668\n",
      "i: 71 average precision: 0.8835834439511902\n",
      "i: 72 average precision: 0.8833152127906148\n",
      "i: 73 average precision: 0.8830525931834281\n",
      "i: 74 average precision: 0.8830382972947054\n",
      "i: 75 average precision: 0.8826668273716883\n",
      "i: 76 average precision: 0.8827744562753058\n",
      "i: 77 average precision: 0.8831907939036485\n",
      "i: 78 average precision: 0.8830707549502361\n",
      "i: 79 average precision: 0.8830145452630055\n",
      "i: 80 average precision: 0.8832059293517655\n",
      "i: 81 average precision: 0.8834438494458982\n",
      "i: 82 average precision: 0.8834672387926767\n",
      "i: 83 average precision: 0.883214537227961\n"
     ]
    }
   ],
   "source": [
    "max_precision = 0\n",
    "\n",
    "from dataframe import calculate_attributes\n",
    "\n",
    "for i in range(1,100):\n",
    "    jds_similarities = []\n",
    "    for j in range(len(jds)):\n",
    "        jds_similarities.append(calculate_attributes.get_jds_sts_percentage_ranking_similarities(jds[j][0][:i],jds[j][1][:i]))\n",
    "    \n",
    "    df['jds_similarity'] = jds_similarities\n",
    "\n",
    "    # normalize\n",
    "    df['namespace_size'] = common_functions.normalize(df['namespace_size'])\n",
    "    df['last_name_length'] = common_functions.normalize(df['last_name_length'])\n",
    "    df['year_difference'] = common_functions.normalize(df['year_difference'])\n",
    "\n",
    "    # save csv\n",
    "    df_to_save = df.drop(['CT', 'PubMed', 'ct_last_name', 'ct_first_name_initial', 'ct_first_name',\n",
    "          'ct_organization', 'ct_mail', 'ct_year', 'ct_initials', 'ct_title', 'ct_country', 'ct_city', \n",
    "            'ar_last_name','ar_first_name_initial','ar_first_name','ar_organization', 'ar_mail', 'ar_initials',\n",
    "                  'ar_year', 'ar_title', 'ar_location'], axis = 1)\n",
    "    csv = df_to_save.to_csv(index=False)\n",
    "    file = codecs.open(\"dataframe.csv\", \"w\", \"utf-8\")\n",
    "    file.write(csv)\n",
    "    file.close()\n",
    "\n",
    "    # model\n",
    "    df_model = pd.read_csv('dataframe.csv', encoding = 'utf-8')\n",
    "    x = df_model.drop('common_answer', axis=1)\n",
    "    y = df_model['common_answer']\n",
    "\n",
    "    avg_precision = 0\n",
    "    for k in range(100):\n",
    "        x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.33, random_state = k)\n",
    "        classifier = RandomForest(0)\n",
    "        classifier.create_model(x_train, y_train)\n",
    "        pred = classifier.predict(x_test)\n",
    "        avg_precision += precision_recall_fscore_support(y_test, pred, average='weighted')[0]\n",
    "    avg_precision /= 100\n",
    "\n",
    "    print(\"i:\",i,\"average precision:\",avg_precision)\n",
    "\n",
    "    if avg_precision > max_precision:\n",
    "        max_precision = avg_precision\n",
    "        best_i = i\n",
    "        \n",
    "print(best_i)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "importlib.reload(article_info)\n",
    "importlib.reload(ct_info)\n",
    "importlib.reload(calculate_attributes)\n",
    "importlib.reload(clinical_trial)\n",
    "importlib.reload(common_functions)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
